version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3100:80"
    environment:
      - NODE_ENV=staging
      - REACT_APP_API_BASE_URL=https://staging-api.example.com/api
    restart: unless-stopped
    networks:
      - app-network-staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network-staging:
    driver: bridge
