# CESE 后端服务生产环境配置

# 服务配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "release" # release模式

# 数据库配置
database:
  host: "${CESE_DATABASE_HOST:localhost}"
  port: ${CESE_DATABASE_PORT:3306}
  username: "${CESE_DATABASE_USERNAME:cese_user}"
  password: "${CESE_DATABASE_PASSWORD}"
  database: "${CESE_DATABASE_DATABASE:cese}"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 7200 # 2小时

# JWT配置
jwt:
  secret: "${CESE_JWT_SECRET}"
  expire_hours: 24 # Token过期时间（小时）
  refresh_expire_hours: 168 # 刷新Token过期时间（7天）

# 日志配置
log:
  level: "info" # 生产环境使用info级别
  format: "json" # JSON格式便于日志收集
  output: "file" # 输出到文件
  file_path: "/var/log/cese/app.log"
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # 天
  compress: true

# 分页配置
pagination:
  default_page: 1
  default_size: 15
  max_size: 100

# 密码配置
password:
  min_length: 8
  max_length: 16
  require_number: true
  require_lower: true
  require_upper: true
  require_special: true

# Redis配置（缓存和限流）
redis:
  host: "${CESE_REDIS_HOST:localhost}"
  port: ${CESE_REDIS_PORT:6379}
  password: "${CESE_REDIS_PASSWORD:}"
  database: 0
  pool_size: 20
  min_idle_conns: 5

# 限流配置
rate_limit:
  enabled: true
  # 全局限流：每分钟1000次请求
  global:
    requests: 1000
    window: "1m"
  # API限流配置
  apis:
    # 登录接口：每分钟10次
    "/api/v1/user/login":
      requests: 10
      window: "1m"
    # 注册接口：每小时5次
    "/api/v1/user/register":
      requests: 5
      window: "1h"
    # 其他接口：每分钟100次
    "default":
      requests: 100
      window: "1m"

# 安全配置
security:
  # CORS配置
  cors:
    allowed_origins: ["https://yourdomain.com"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization"]
    max_age: 86400
  # 请求大小限制
  max_request_size: "10MB"
  # 超时配置
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# 监控配置
monitoring:
  # 健康检查
  health_check:
    enabled: true
    path: "/health"
  # 指标收集
  metrics:
    enabled: true
    path: "/metrics"
  # 链路追踪
  tracing:
    enabled: true
    jaeger_endpoint: "${JAEGER_ENDPOINT:}"

# 邮件配置（用于通知）
email:
  smtp_host: "${SMTP_HOST:}"
  smtp_port: ${SMTP_PORT:587}
  username: "${SMTP_USERNAME:}"
  password: "${SMTP_PASSWORD:}"
  from: "${EMAIL_FROM:noreply@yourdomain.com}"
